//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CulturAppEscritorio.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_room
    {
        public int room_id { get; set; }
        public int inventory_id { get; set; }
        public int quantity { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
