//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CulturAppEscritorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Events()
        {
            this.Booking = new HashSet<Booking>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public System.DateTime start_datetime { get; set; }
        public System.DateTime end_datetime { get; set; }
        public int capacity { get; set; }
        public string description { get; set; }
        public int price { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> room_id { get; set; }
        public Nullable<int> type_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Booking { get; set; }
        public virtual Rooms Rooms { get; set; }
        public virtual Type_event Type_event { get; set; }
    }
}
